channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::java-jdk=8.0.112
  - bioconda::illumina-interop=1.1.23
  - conda-forge::dask=2021.3.0
  - conda-forge::distributed=2021.3.0
  - pip
  - pip:
    - jupyterlab==3.1.7
    - nbconvert==6.0.7
    - iplotter==0.4.3
    - gviz-api==1.9.0
    - pyspark==3.1.2
    - Jinja2==3.0.1
    - pyarrow==5.0.0
    - dask-labextension==5.1.0