channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::illumina-interop=1.1.21
  - pip
  - pip:
    - jupyterlab>=3.0.0
    - nbconvert[webpdf]>=6.0.0
    - iplotter==0.4.3
    - gviz-api==1.9.0
