channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::illumina-interop=1.1.21
  - pip
  - pip:
    - iplotter==0.4.3
    - pyppeteer==0.2.5
    - gviz-api==1.9.0 
    - nbconvert[webpdf]
    - plotly==4.14.3
    - ipywidgets>=7.5
